apiVersion: v1
kind: Service
metadata:
  name: mynodejsapp
  labels:
    app: mynodejsapp
spec:
  type: NodePort #Exposes the service as a node ports
  ports:
  - port: 3000
    nodePort: 32411
    protocol: TCP
    targetPort: 3000
  selector:
    app: webapp
